[rule]
author = "fab"
description = """
required field only.
"""
from = "now-6m" #this is the default value
index = ["logs-*", "*endpoint-*"]

name = "Suspicious Inter-Process Communication via Outlook"
note = "note for analyst"
risk_score = 47
severity = "medium"
tags = ["TTPs", "Windows", "Outlook"]
type = "eql"
query = '''
sequence with maxspan=1m
[process where host.os.type == "windows" and event.action == "start" and
  (
    process.name : (
      "rundll32.exe", "mshta.exe", "powershell.exe", "pwsh.exe",
      "cmd.exe", "regsvr32.exe", "cscript.exe", "wscript.exe"
    ) or
    (
      (process.code_signature.trusted == false or process.code_signature.exists == false) and
      (process.Ext.relative_file_creation_time <= 500 or process.Ext.relative_file_name_modify_time <= 500)
    )
  )
] by process.entity_id
[process where host.os.type == "windows" and event.action == "start" and process.name : "OUTLOOK.EXE" and
  process.Ext.effective_parent.name != null] by process.Ext.effective_parent.entity_id
'''

[[rule.threat]]
framework = "MITRE ATT&CK" 
[[rule.threat.technique]]
id = "T1055"
name = "Process Injection"
[[rule.threat.subtechnique]]
id = "T1055.001"
name = "Dynamic-link Library Injection"

[[rule.threat.tactic]]
id = "TA0002"
name = "Execution"


#if type = "thresold"
# threshold = 7d
#version = 1
#interval = 5m
